name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI Server
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
          sleep 10
          curl --retry 5 --retry-delay 5 --retry-connrefused http://127.0.0.1:8000/docs

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start Ngrok
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 8000 > ngrok.log 2>&1 &

      - name: Display Ngrok URL
        run: |
          sleep 5
          sudo apt-get install -y jq
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
